# training_config.yaml
learning_rate: 0.01
epochs: 100
batch_size: 32
train_data_path: "data/processed/training_data.csv"
validation_data_path: "data/processed/validation_data.csv"
test_data_path: "data/processed/test_data.csv"
